version: "3.3"

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./.ipfs:/data/ipfs
    environment:
      IPFS_PROFILE: server
    ports:
      - "5001:5001"
    command:
      [
        "daemon",
        "--migrate=true",
        "--enable-pubsub-experiment",
        "--enable-gc",
        "--routing=dhtclient"
      ]

  server:
    depends_on:
      - ipfs
    links:
      - ipfs
    build: .
    command: [ "-g", "http://ipfs:5001" ]
 